### ISSUE TITLE
Why does the seahorse flatpak need `device=dri` GPU acceleration?

### ISSUE THREAD

**Issue by Apacelus** [flathub/org.gnome.seahorse.Application#13]
Why does a "simple" (compared to say, a video editor) gui app need gpu acceleration?

Disabling that permission does not seem to slow down the app

**Comment by nielsdg** [comment]
Because "simple" applications still like to use OpenGL and other related graphics APIs for hardware accelerated rendering.

Like you mentioned already, it's possible to render without those APIs, but that's basically letting your CPU do work that your GPU can do much more efficiently.

If need be, people can remove the access manually if they want to, but they don't get to complain about any performance impact though. Note that when we have finished the GTK4 port in a future release, that might not work anymore however.
