### ISSUE TITLE
Potentially unnecessary permission

### ISSUE THREAD

**Issue by rotilho** [flathub/org.gnome.seahorse.Application#19]
I noticed that this package requires `--device=dri`, is it really necessary? I disabled it and everything seems to be working as expected.

**Comment by nielsdg** [comment]
It's used for being able to use hardware accelerated rendering (OpenGL etc). It will work _without_ access to it, since it will then just fall back to (CPU-based) software rendering, but that's going to be slower and using your CPU for something a GPU can do much more power-efficient, and faster :-)
